FROM ghcr.io/ggml-org/llama.cpp:server


ENV LLAMA_ARG_HOST=::
ENV LLAMA_ARG_PORT=8000
ENV LLAMA_ARG_NO_WEBUI=1
ENV LLAMA_ARG_JINJA=1
ENV LLAMA_ARG_HF_REPO=$LLAMA_ARG_HF_REPO
ENV LLAMA_CHAT_TEMPLATE_KWARGS='{"reasoning_effort":"low","builtin_tools":["python","browser"]}'
ENV PYTHON_EXECUTION_BACKEND=UV
ENV EXA_API_KEY=$EXA_API_KEY
ENV LLAMA_API_KEY=$LLAMA_API_KEY

EXPOSE 8000/tcp

ENTRYPOINT [ "./llama-server" ]
